//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 22/04/2014 20:19:51
namespace AppliFrais
{
    
    /// <summary>
    /// There are no comments for applifraisEntities1 in the schema.
    /// </summary>
    public partial class applifraisEntities1 : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new applifraisEntities1 object using the connection string found in the 'applifraisEntities1' section of the application configuration file.
        /// </summary>
        public applifraisEntities1() : 
                base("name=applifraisEntities1", "applifraisEntities1")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new applifraisEntities1 object.
        /// </summary>
        public applifraisEntities1(string connectionString) : 
                base(connectionString, "applifraisEntities1")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new applifraisEntities1 object.
        /// </summary>
        public applifraisEntities1(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "applifraisEntities1")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for etat in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<etat> etat
        {
            get
            {
                if ((this._etat == null))
                {
                    this._etat = base.CreateQuery<etat>("[etat]");
                }
                return this._etat;
            }
        }
        private global::System.Data.Objects.ObjectQuery<etat> _etat;
        /// <summary>
        /// There are no comments for fichefrais in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<fichefrais> fichefrais
        {
            get
            {
                if ((this._fichefrais == null))
                {
                    this._fichefrais = base.CreateQuery<fichefrais>("[fichefrais]");
                }
                return this._fichefrais;
            }
        }
        private global::System.Data.Objects.ObjectQuery<fichefrais> _fichefrais;
        /// <summary>
        /// There are no comments for fraisforfait in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<fraisforfait> fraisforfait
        {
            get
            {
                if ((this._fraisforfait == null))
                {
                    this._fraisforfait = base.CreateQuery<fraisforfait>("[fraisforfait]");
                }
                return this._fraisforfait;
            }
        }
        private global::System.Data.Objects.ObjectQuery<fraisforfait> _fraisforfait;
        /// <summary>
        /// There are no comments for lignefraisforfait in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<lignefraisforfait> lignefraisforfait
        {
            get
            {
                if ((this._lignefraisforfait == null))
                {
                    this._lignefraisforfait = base.CreateQuery<lignefraisforfait>("[lignefraisforfait]");
                }
                return this._lignefraisforfait;
            }
        }
        private global::System.Data.Objects.ObjectQuery<lignefraisforfait> _lignefraisforfait;
        /// <summary>
        /// There are no comments for lignefraishorsforfait in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<lignefraishorsforfait> lignefraishorsforfait
        {
            get
            {
                if ((this._lignefraishorsforfait == null))
                {
                    this._lignefraishorsforfait = base.CreateQuery<lignefraishorsforfait>("[lignefraishorsforfait]");
                }
                return this._lignefraishorsforfait;
            }
        }
        private global::System.Data.Objects.ObjectQuery<lignefraishorsforfait> _lignefraishorsforfait;
        /// <summary>
        /// There are no comments for visiteur in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<visiteur> visiteur
        {
            get
            {
                if ((this._visiteur == null))
                {
                    this._visiteur = base.CreateQuery<visiteur>("[visiteur]");
                }
                return this._visiteur;
            }
        }
        private global::System.Data.Objects.ObjectQuery<visiteur> _visiteur;
        /// <summary>
        /// There are no comments for etat in the schema.
        /// </summary>
        public void AddToetat(etat etat)
        {
            base.AddObject("etat", etat);
        }
        /// <summary>
        /// There are no comments for fichefrais in the schema.
        /// </summary>
        public void AddTofichefrais(fichefrais fichefrais)
        {
            base.AddObject("fichefrais", fichefrais);
        }
        /// <summary>
        /// There are no comments for fraisforfait in the schema.
        /// </summary>
        public void AddTofraisforfait(fraisforfait fraisforfait)
        {
            base.AddObject("fraisforfait", fraisforfait);
        }
        /// <summary>
        /// There are no comments for lignefraisforfait in the schema.
        /// </summary>
        public void AddTolignefraisforfait(lignefraisforfait lignefraisforfait)
        {
            base.AddObject("lignefraisforfait", lignefraisforfait);
        }
        /// <summary>
        /// There are no comments for lignefraishorsforfait in the schema.
        /// </summary>
        public void AddTolignefraishorsforfait(lignefraishorsforfait lignefraishorsforfait)
        {
            base.AddObject("lignefraishorsforfait", lignefraishorsforfait);
        }
        /// <summary>
        /// There are no comments for visiteur in the schema.
        /// </summary>
        public void AddTovisiteur(visiteur visiteur)
        {
            base.AddObject("visiteur", visiteur);
        }
    }
    /// <summary>
    /// There are no comments for applifraisModel.etat in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="applifraisModel", Name="etat")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class etat : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new etat object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        public static etat Createetat(int id)
        {
            etat etat = new etat();
            etat.id = id;
            return etat;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property libelle in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string libelle
        {
            get
            {
                return this._libelle;
            }
            set
            {
                this.OnlibelleChanging(value);
                this.ReportPropertyChanging("libelle");
                this._libelle = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("libelle");
                this.OnlibelleChanged();
            }
        }
        private string _libelle;
        partial void OnlibelleChanging(string value);
        partial void OnlibelleChanged();
    }
    /// <summary>
    /// There are no comments for applifraisModel.fichefrais in the schema.
    /// </summary>
    /// <KeyProperties>
    /// idVisiteur
    /// mois
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="applifraisModel", Name="fichefrais")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class fichefrais : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new fichefrais object.
        /// </summary>
        /// <param name="idVisiteur">Initial value of idVisiteur.</param>
        /// <param name="mois">Initial value of mois.</param>
        public static fichefrais Createfichefrais(int idVisiteur, string mois)
        {
            fichefrais fichefrais = new fichefrais();
            fichefrais.idVisiteur = idVisiteur;
            fichefrais.mois = mois;
            return fichefrais;
        }
        /// <summary>
        /// There are no comments for Property idVisiteur in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int idVisiteur
        {
            get
            {
                return this._idVisiteur;
            }
            set
            {
                this.OnidVisiteurChanging(value);
                this.ReportPropertyChanging("idVisiteur");
                this._idVisiteur = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idVisiteur");
                this.OnidVisiteurChanged();
            }
        }
        private int _idVisiteur;
        partial void OnidVisiteurChanging(int value);
        partial void OnidVisiteurChanged();
        /// <summary>
        /// There are no comments for Property mois in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string mois
        {
            get
            {
                return this._mois;
            }
            set
            {
                this.OnmoisChanging(value);
                this.ReportPropertyChanging("mois");
                this._mois = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("mois");
                this.OnmoisChanged();
            }
        }
        private string _mois;
        partial void OnmoisChanging(string value);
        partial void OnmoisChanged();
        /// <summary>
        /// There are no comments for Property nbJustificatifs in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> nbJustificatifs
        {
            get
            {
                return this._nbJustificatifs;
            }
            set
            {
                this.OnnbJustificatifsChanging(value);
                this.ReportPropertyChanging("nbJustificatifs");
                this._nbJustificatifs = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("nbJustificatifs");
                this.OnnbJustificatifsChanged();
            }
        }
        private global::System.Nullable<int> _nbJustificatifs;
        partial void OnnbJustificatifsChanging(global::System.Nullable<int> value);
        partial void OnnbJustificatifsChanged();
        /// <summary>
        /// There are no comments for Property montantValide in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<double> montantValide
        {
            get
            {
                return this._montantValide;
            }
            set
            {
                this.OnmontantValideChanging(value);
                this.ReportPropertyChanging("montantValide");
                this._montantValide = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("montantValide");
                this.OnmontantValideChanged();
            }
        }
        private global::System.Nullable<double> _montantValide;
        partial void OnmontantValideChanging(global::System.Nullable<double> value);
        partial void OnmontantValideChanged();
        /// <summary>
        /// There are no comments for Property dateModif in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> dateModif
        {
            get
            {
                return this._dateModif;
            }
            set
            {
                this.OndateModifChanging(value);
                this.ReportPropertyChanging("dateModif");
                this._dateModif = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("dateModif");
                this.OndateModifChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _dateModif;
        partial void OndateModifChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OndateModifChanged();
        /// <summary>
        /// There are no comments for Property idEtat in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> idEtat
        {
            get
            {
                return this._idEtat;
            }
            set
            {
                this.OnidEtatChanging(value);
                this.ReportPropertyChanging("idEtat");
                this._idEtat = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idEtat");
                this.OnidEtatChanged();
            }
        }
        private global::System.Nullable<int> _idEtat;
        partial void OnidEtatChanging(global::System.Nullable<int> value);
        partial void OnidEtatChanged();
    }
    /// <summary>
    /// There are no comments for applifraisModel.fraisforfait in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="applifraisModel", Name="fraisforfait")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class fraisforfait : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new fraisforfait object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        public static fraisforfait Createfraisforfait(int id)
        {
            fraisforfait fraisforfait = new fraisforfait();
            fraisforfait.id = id;
            return fraisforfait;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property libelle in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string libelle
        {
            get
            {
                return this._libelle;
            }
            set
            {
                this.OnlibelleChanging(value);
                this.ReportPropertyChanging("libelle");
                this._libelle = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("libelle");
                this.OnlibelleChanged();
            }
        }
        private string _libelle;
        partial void OnlibelleChanging(string value);
        partial void OnlibelleChanged();
        /// <summary>
        /// There are no comments for Property montant in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<double> montant
        {
            get
            {
                return this._montant;
            }
            set
            {
                this.OnmontantChanging(value);
                this.ReportPropertyChanging("montant");
                this._montant = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("montant");
                this.OnmontantChanged();
            }
        }
        private global::System.Nullable<double> _montant;
        partial void OnmontantChanging(global::System.Nullable<double> value);
        partial void OnmontantChanged();
    }
    /// <summary>
    /// There are no comments for applifraisModel.lignefraisforfait in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="applifraisModel", Name="lignefraisforfait")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class lignefraisforfait : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new lignefraisforfait object.
        /// </summary>
        /// <param name="idVisiteur">Initial value of idVisiteur.</param>
        /// <param name="mois">Initial value of mois.</param>
        /// <param name="idFraisForfait">Initial value of idFraisForfait.</param>
        /// <param name="id">Initial value of id.</param>
        public static lignefraisforfait Createlignefraisforfait(int idVisiteur, string mois, int idFraisForfait, int id)
        {
            lignefraisforfait lignefraisforfait = new lignefraisforfait();
            lignefraisforfait.idVisiteur = idVisiteur;
            lignefraisforfait.mois = mois;
            lignefraisforfait.idFraisForfait = idFraisForfait;
            lignefraisforfait.id = id;
            return lignefraisforfait;
        }
        /// <summary>
        /// There are no comments for Property idVisiteur in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int idVisiteur
        {
            get
            {
                return this._idVisiteur;
            }
            set
            {
                this.OnidVisiteurChanging(value);
                this.ReportPropertyChanging("idVisiteur");
                this._idVisiteur = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idVisiteur");
                this.OnidVisiteurChanged();
            }
        }
        private int _idVisiteur;
        partial void OnidVisiteurChanging(int value);
        partial void OnidVisiteurChanged();
        /// <summary>
        /// There are no comments for Property mois in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string mois
        {
            get
            {
                return this._mois;
            }
            set
            {
                this.OnmoisChanging(value);
                this.ReportPropertyChanging("mois");
                this._mois = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("mois");
                this.OnmoisChanged();
            }
        }
        private string _mois;
        partial void OnmoisChanging(string value);
        partial void OnmoisChanged();
        /// <summary>
        /// There are no comments for Property idFraisForfait in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int idFraisForfait
        {
            get
            {
                return this._idFraisForfait;
            }
            set
            {
                this.OnidFraisForfaitChanging(value);
                this.ReportPropertyChanging("idFraisForfait");
                this._idFraisForfait = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idFraisForfait");
                this.OnidFraisForfaitChanged();
            }
        }
        private int _idFraisForfait;
        partial void OnidFraisForfaitChanging(int value);
        partial void OnidFraisForfaitChanged();
        /// <summary>
        /// There are no comments for Property quantite in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> quantite
        {
            get
            {
                return this._quantite;
            }
            set
            {
                this.OnquantiteChanging(value);
                this.ReportPropertyChanging("quantite");
                this._quantite = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("quantite");
                this.OnquantiteChanged();
            }
        }
        private global::System.Nullable<int> _quantite;
        partial void OnquantiteChanging(global::System.Nullable<int> value);
        partial void OnquantiteChanged();
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property reporter in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> reporter
        {
            get
            {
                return this._reporter;
            }
            set
            {
                this.OnreporterChanging(value);
                this.ReportPropertyChanging("reporter");
                this._reporter = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("reporter");
                this.OnreporterChanged();
            }
        }
        private global::System.Nullable<int> _reporter;
        partial void OnreporterChanging(global::System.Nullable<int> value);
        partial void OnreporterChanged();
        /// <summary>
        /// There are no comments for Property idEtat in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> idEtat
        {
            get
            {
                return this._idEtat;
            }
            set
            {
                this.OnidEtatChanging(value);
                this.ReportPropertyChanging("idEtat");
                this._idEtat = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idEtat");
                this.OnidEtatChanged();
            }
        }
        private global::System.Nullable<int> _idEtat;
        partial void OnidEtatChanging(global::System.Nullable<int> value);
        partial void OnidEtatChanged();
    }
    /// <summary>
    /// There are no comments for applifraisModel.lignefraishorsforfait in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="applifraisModel", Name="lignefraishorsforfait")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class lignefraishorsforfait : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new lignefraishorsforfait object.
        /// </summary>
        /// <param name="idVisiteur">Initial value of idVisiteur.</param>
        /// <param name="mois">Initial value of mois.</param>
        /// <param name="id">Initial value of id.</param>
        public static lignefraishorsforfait Createlignefraishorsforfait(int idVisiteur, string mois, int id)
        {
            lignefraishorsforfait lignefraishorsforfait = new lignefraishorsforfait();
            lignefraishorsforfait.idVisiteur = idVisiteur;
            lignefraishorsforfait.mois = mois;
            lignefraishorsforfait.id = id;
            return lignefraishorsforfait;
        }
        /// <summary>
        /// There are no comments for Property idVisiteur in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int idVisiteur
        {
            get
            {
                return this._idVisiteur;
            }
            set
            {
                this.OnidVisiteurChanging(value);
                this.ReportPropertyChanging("idVisiteur");
                this._idVisiteur = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idVisiteur");
                this.OnidVisiteurChanged();
            }
        }
        private int _idVisiteur;
        partial void OnidVisiteurChanging(int value);
        partial void OnidVisiteurChanged();
        /// <summary>
        /// There are no comments for Property mois in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string mois
        {
            get
            {
                return this._mois;
            }
            set
            {
                this.OnmoisChanging(value);
                this.ReportPropertyChanging("mois");
                this._mois = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("mois");
                this.OnmoisChanged();
            }
        }
        private string _mois;
        partial void OnmoisChanging(string value);
        partial void OnmoisChanged();
        /// <summary>
        /// There are no comments for Property libelle in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string libelle
        {
            get
            {
                return this._libelle;
            }
            set
            {
                this.OnlibelleChanging(value);
                this.ReportPropertyChanging("libelle");
                this._libelle = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("libelle");
                this.OnlibelleChanged();
            }
        }
        private string _libelle;
        partial void OnlibelleChanging(string value);
        partial void OnlibelleChanged();
        /// <summary>
        /// There are no comments for Property date in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> date
        {
            get
            {
                return this._date;
            }
            set
            {
                this.OndateChanging(value);
                this.ReportPropertyChanging("date");
                this._date = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("date");
                this.OndateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _date;
        partial void OndateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OndateChanged();
        /// <summary>
        /// There are no comments for Property montant in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<double> montant
        {
            get
            {
                return this._montant;
            }
            set
            {
                this.OnmontantChanging(value);
                this.ReportPropertyChanging("montant");
                this._montant = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("montant");
                this.OnmontantChanged();
            }
        }
        private global::System.Nullable<double> _montant;
        partial void OnmontantChanging(global::System.Nullable<double> value);
        partial void OnmontantChanged();
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property reporter in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> reporter
        {
            get
            {
                return this._reporter;
            }
            set
            {
                this.OnreporterChanging(value);
                this.ReportPropertyChanging("reporter");
                this._reporter = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("reporter");
                this.OnreporterChanged();
            }
        }
        private global::System.Nullable<int> _reporter;
        partial void OnreporterChanging(global::System.Nullable<int> value);
        partial void OnreporterChanged();
        /// <summary>
        /// There are no comments for Property idEtat in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> idEtat
        {
            get
            {
                return this._idEtat;
            }
            set
            {
                this.OnidEtatChanging(value);
                this.ReportPropertyChanging("idEtat");
                this._idEtat = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idEtat");
                this.OnidEtatChanged();
            }
        }
        private global::System.Nullable<int> _idEtat;
        partial void OnidEtatChanging(global::System.Nullable<int> value);
        partial void OnidEtatChanged();
    }
    /// <summary>
    /// There are no comments for applifraisModel.visiteur in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="applifraisModel", Name="visiteur")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class visiteur : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new visiteur object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        public static visiteur Createvisiteur(int id)
        {
            visiteur visiteur = new visiteur();
            visiteur.id = id;
            return visiteur;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property nom in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string nom
        {
            get
            {
                return this._nom;
            }
            set
            {
                this.OnnomChanging(value);
                this.ReportPropertyChanging("nom");
                this._nom = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("nom");
                this.OnnomChanged();
            }
        }
        private string _nom;
        partial void OnnomChanging(string value);
        partial void OnnomChanged();
        /// <summary>
        /// There are no comments for Property prenom in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string prenom
        {
            get
            {
                return this._prenom;
            }
            set
            {
                this.OnprenomChanging(value);
                this.ReportPropertyChanging("prenom");
                this._prenom = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("prenom");
                this.OnprenomChanged();
            }
        }
        private string _prenom;
        partial void OnprenomChanging(string value);
        partial void OnprenomChanged();
        /// <summary>
        /// There are no comments for Property login in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string login
        {
            get
            {
                return this._login;
            }
            set
            {
                this.OnloginChanging(value);
                this.ReportPropertyChanging("login");
                this._login = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("login");
                this.OnloginChanged();
            }
        }
        private string _login;
        partial void OnloginChanging(string value);
        partial void OnloginChanged();
        /// <summary>
        /// There are no comments for Property mdp in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string mdp
        {
            get
            {
                return this._mdp;
            }
            set
            {
                this.OnmdpChanging(value);
                this.ReportPropertyChanging("mdp");
                this._mdp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("mdp");
                this.OnmdpChanged();
            }
        }
        private string _mdp;
        partial void OnmdpChanging(string value);
        partial void OnmdpChanged();
        /// <summary>
        /// There are no comments for Property adresse in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string adresse
        {
            get
            {
                return this._adresse;
            }
            set
            {
                this.OnadresseChanging(value);
                this.ReportPropertyChanging("adresse");
                this._adresse = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("adresse");
                this.OnadresseChanged();
            }
        }
        private string _adresse;
        partial void OnadresseChanging(string value);
        partial void OnadresseChanged();
        /// <summary>
        /// There are no comments for Property cp in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string cp
        {
            get
            {
                return this._cp;
            }
            set
            {
                this.OncpChanging(value);
                this.ReportPropertyChanging("cp");
                this._cp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("cp");
                this.OncpChanged();
            }
        }
        private string _cp;
        partial void OncpChanging(string value);
        partial void OncpChanged();
        /// <summary>
        /// There are no comments for Property ville in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ville
        {
            get
            {
                return this._ville;
            }
            set
            {
                this.OnvilleChanging(value);
                this.ReportPropertyChanging("ville");
                this._ville = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ville");
                this.OnvilleChanged();
            }
        }
        private string _ville;
        partial void OnvilleChanging(string value);
        partial void OnvilleChanged();
        /// <summary>
        /// There are no comments for Property dateEmbauche in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> dateEmbauche
        {
            get
            {
                return this._dateEmbauche;
            }
            set
            {
                this.OndateEmbaucheChanging(value);
                this.ReportPropertyChanging("dateEmbauche");
                this._dateEmbauche = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("dateEmbauche");
                this.OndateEmbaucheChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _dateEmbauche;
        partial void OndateEmbaucheChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OndateEmbaucheChanged();
        /// <summary>
        /// There are no comments for Property comptable in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<sbyte> comptable
        {
            get
            {
                return this._comptable;
            }
            set
            {
                this.OncomptableChanging(value);
                this.ReportPropertyChanging("comptable");
                this._comptable = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("comptable");
                this.OncomptableChanged();
            }
        }
        private global::System.Nullable<sbyte> _comptable;
        partial void OncomptableChanging(global::System.Nullable<sbyte> value);
        partial void OncomptableChanged();
    }
}
